// app/(routes)/crm/accounts/_data/mockAccounts.ts

import { AccountType } from '../_types';

export const mockAccounts: AccountType[] = [
  {
    id: 'acc-uber-berlin',
    companyName: 'Uber Partner Berlin GmbH',
    legalCompanyName: 'Uber Partner Berlin GmbH',
    street: 'Alexanderstraße 12',
    zipCode: '10117',
    city: 'Berlin',
    country: 'Germany',
    taxId: 'DE123456789',
    website: 'https://uber-partner-berlin.de',
    fleetSizeEstimate: 85,
    status: 'customer',
    lifecycleStage: 'active',
    owner: 'Anh Chu',
    createdAt: '2024-03-12T09:15:00.000Z',
    source: 'Direct / Self-signup',
    summary: 'Key Uber subcontractor in Berlin with 80+ vehicles. Focus on uptime and safety.',
    isCustomer: true,
    customerSince: '2024-03-12',
    stripeCustomerId: 'cus_123456789',
  },
  {
    id: 'acc-munich-shuttle',
    companyName: 'Munich Shuttle Service',
    legalCompanyName: 'Munich Shuttle Service e.K.',
    street: 'Leopoldstraße 45',
    zipCode: '80802',
    city: 'Munich',
    country: 'Germany',
    taxId: 'DE234567890',
    website: 'https://munich-shuttle.de',
    fleetSizeEstimate: 40,
    status: 'prospect',
    lifecycleStage: 'new',
    owner: 'TBD',
    createdAt: '2024-05-01T11:30:00.000Z',
    source: 'Inbound',
    summary: 'Prospect focused on airport shuttles. Early stage conversations.',
    isCustomer: false,
    customerSince: null,
    stripeCustomerId: null,
  },
  {
    id: 'acc-zurich-ride',
    companyName: 'Zurich Ride AG',
    legalCompanyName: 'Zurich Ride AG',
    street: 'Bahnhofstrasse 88',
    zipCode: '8001',
    city: 'Zurich',
    country: 'Switzerland',
    taxId: 'CHE-123.456.789',
    website: 'https://zurich-ride.ch',
    fleetSizeEstimate: 55,
    status: 'customer',
    lifecycleStage: 'expansion',
    owner: 'Anh Chu',
    createdAt: '2023-11-20T14:45:00.000Z',
    source: 'Partner referral',
    summary: 'High-quality Swiss fleet with strong NPS; candidate for expansion and upsell.',
    isCustomer: true,
    customerSince: '2023-11-20',
    stripeCustomerId: 'cus_987654321',
  },
];
